### ISSUE TITLE
Fråga Regeringskansliet om status Rättsinformationsprojektet

### ISSUE THREAD

**Issue by salgo60** [salgo60/LagrummetLight#3]
**Bakgrund:** detta projekt initierades [1996 med en förstudie](https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem) och handlar om interoperabilitet mellan 100 myndigheter som ger ut författningar idag 26 år senare har i princip inget levererats och [domstolsverket som drev detta vet inte status ](https://github.com/salgo60/open-data-examples/issues/2#issuecomment-1175362343) och pekar på Regeringskansliet .... Regeringskansliet säger att dom på 6 år av översyn inte kan delge oss status

**Status 2024-maj på förfrågan:** [Granskning begärd av Regeringskansliets arbete](https://github.com/salgo60/LagrummetLight/issues/3#issuecomment-1359381679) 2022 dec 20 - **Jag antar att det är ett exempel på tjänstemannens förhalning att inte återkoppla på en fråga om varför inget har hänt efter 20 år**

----

* 2022 pratar vi mycket om [interoperabilitet](https://community.dataportal.se/topic/599/interoperable-europe-act) vilket detta projekt var ett exempel på som sagt det tar > 15 år för 100 myndigheter att inse att man inte har en infrastruktur och kompetens att skapa interoperabiltet för en dokument typ författningar och idag > 26 år efter förstudien starta verkar det vara svårt att hitta vad som hänt med [SFS 1999:175](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175) och om Sverige skall bli del av ELI
  * 2019 skapas en digital expert myndighet DIGG som inte verkar arbeta datadrivet och idag 2022 dec inte levererar [sina författningar MDFS](https://www.digg.se/om-oss/forfattningssamling) enligt med [SFS 1999:175](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175) som öppna data (länk [DIGGs 4 datamängder som är öppna data](https://www.dataportal.se/sv/datasets?p=1&q=&s=2&t=20&f=http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fpublisher%7C%7Chttps%3A%2F%2Fcatalog.digg.se%2Fstore%2F1%2Fresource%2F1%7C%7Cfalse%7C%7Curi%7C%7COrganisation%7C%7CMyndigheten%20f%C3%B6r%20digital%20f%C3%B6rvaltning&rt=dataset%24esterms_IndependentDataService%24esterms_ServedByDataService&c=false)) 
      * 2022 pratas det om [interoperabiltet](https://community.dataportal.se/topic/599/interoperable-europe-act), [5 star data och kunskapsgrafer](https://github.com/salgo60/DiggUptime/issues/85) dvs. de visioner som anges i [DS 1998:10](https://web.archive.org/web/20220811093437/https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem) är idag att [alla EU:s författningar skall kopplas ihop med ELI](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/75) och att [gemensamma vokabulär skall användas](https://github.com/salgo60/DiggUptime/issues/51).
    * ... senaste pusselbiten i den oförmåga som verkar finnas är att [en myndighetsanalys görs av den nya expert myndigheten för digital förvaltning DIGG som funnits i 3 år om DIGG fullgör sina uppgifter och hur samverkan sker mellan myndigheten och andra myndigheter, kommuner...](https://www.regeringen.se/4ae0ac/contentassets/2632a59bd82841bb9e1ef4e9108e1866/uppdrag-att-utfora-en-myndighetsanalys-av-myndigheten-for-digital-forvaltning) - enligt deras egen personal gar dom på 3 år inte lyckats skapa ett intranet....
----
**Brev Regeringskansliet #3**

* [Handlingar.se](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19) 7 dec 2022

Till Regeringskansliet,

Enligt [Domstolverkets svar till mig 2022-jul](https://github.com/salgo60/open-data-examples/issues/2#issuecomment-1175362343) citat "I Regeringskansliet pågår sedan några år tillbaka en översyn av rättsinformationsförordningen" jag hittar inte detta i listan över pågående "[Lista på digitaliseringsprojekt](https://handlingar.se/sv/request/lista_pa_digitaliseringsprojekt#incoming-4702
)" ni skickade 6 december 2022

**Fråga 1** pågår arbete med "översyn av rättsinformationsförordningen"
**Fråga 2** projektnummer
**Fråga 3** när skall det redovisas
**Fråga 4** var kan vi följa detta arbete finns projektyta
**Fråga 5** har delresultat publicerats
**Fråga 6** är ELI en del av detta

**Bakgrund** 
Förarbete [DS 1998:10](https://web.archive.org/web/20220811093437/https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem) pekade på problem med det Svenska rättsinformationssystemet och detta leder till [SFS 1999:175](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175) som sedan Domstolsverket driver för att 100 myndigheter med rätt att föreskriva författningar skall implementera detta att leverera sina författningar till lagrummet. Efter > 15 år 2016 verkar någon tagit beslut att 100 myndigheter inte klarar av att leverera sina författningar till lagrummet och [projektet stoppas](https://github.com/rinfo/rdl/commit/21131dde010476c7c090e85a4ec50fb4738fc261) --> att myndigheter som upphört deras författningar [vet inte Domstolsverket var de finns idag 2022](url) etc...  alla tankar i [DS 1998:10](https://web.archive.org/web/20220811093437/https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem) blev efter 18 års jobb med 100 myndigheter [endast 100 länkar](https://lagrummet.se/lagrummet/rattsinformation/myndigheters-foreskrifter) och vi har idag 2022 inga kopplingar till ELI. Finns det en analys varför?

På fråga 2022 refererar [Domstolsverket till att Regeringskansliet](https://github.com/salgo60/open-data-examples/issues/2#issuecomment-1175362343) driver detta men som sagt vi kan inte hitta detta projekt i den [lista över digitaliseringsprojekt ni redovisar 2022 dec 6](https://handlingar.se/sv/request/lista_pa_digitaliseringsprojekt#incoming-4702)

Om utlämnandet är förknippat med en kostnad vill jag ha information om
villkoren för avgiften innan utlämnandet sker.

Med vänlig hälsning,

Magnus Sälgö
Tel: 0735152802

1) Svar Domstolsverket 2022 jul https://github.com/salgo60/open-data-examples/issues/2#issuecomment-1175362343

2) [Översikt av mig vad som hände med SFS 1999:175](https://github.com/salgo60/LagrummetLight) efter > 15 år 2016 verkar någon tagit beslut att 100 myndigheter inte klarar av att leverera sina författningar till lagrummet. Idag 2022 refererar Domstolsverket till att Regeringskansliet driver detta men som sagt vi kan inte hitta detta projekt i den [lista över digitaliseringsprojekt ni redovisar 2022 dec 6](https://handlingar.se/sv/request/lista_pa_digitaliseringsprojekt#incoming-4702)

3) [EUs översikt vilka länder som implementerat ELI](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/info/ELI%20ELI-DL.md) där Sverige inte ingår och [frågar jag EU så vet dom inte ens vem i Sverige dom skall prata med](https://youtu.be/Nk5U2Vm3g54?t=4881)

4) [Riksarkivet svar](https://github.com/Riksarkivet/dataplattform/issues/11) på att dom borde kunna hantera arkiverade myndigheters dokument som dokument och kunna skapa "citation graphs" och bevara [persistenta identifierare](https://github.com/salgo60/DiggUptime/issues/68) och kunna skapa "[citation graphs](https://github.com/salgo60/DiggUptime/issues/85)"

5) Regeringskansliet svar [2022 dec 6 om pågående digitaliseringsprojekt](https://handlingar.se/sv/request/lista_pa_digitaliseringsprojekt#incoming-4702)

Min ref: https://github.com/salgo60/LagrummetLight/issues/3

**Comment by salgo60** [comment]
![image](https://user-images.githubusercontent.com/14206509/206193625-cfc1ba23-981f-436a-972b-a515fba02193.png)

**Comment by salgo60** [comment]
Länkade denna issue från [forum.civictech.se](https://forum.civictech.se/t/myndighetsanalys-av-digg/507)

**Comment by salgo60** [comment]
**Svar [Justitiedepartementet 2022 dec 13](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19#incoming-4714)**
* jag tolkar det som Justitiedepartementet inte gör något utan skickar tillbaka frågan till Regeringskansliet

[Handlingar.se](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19)
---
>Tack för ditt mejl med begäran om att få ta del av handlingar och med frågor om översyn av rättsinformationsförordningen m.m. 
>Av rättsinformationsförordningen (1999:175) följer att det ska finnas ett rättsinformationssystem som ska innehålla viss grundläggande rättsinformation genom ett allmänt nätverk. Domstolsverket är samordningsmyndighet för systemet (15 §) och administrerar webbplatsen lagrummet.se. I den egenskapen ansvarar Domstolsverket bland annat för samordning av frågor om standardisering samt avgör om den obligatoriska informationen uppfyller kraven enligt förordningen m.m. (16 §).
I budgetpropositionen för 2017 redovisade regeringen att det i Regeringskansliet pågår en översyn av rättsinformationsförordningen (prop. 2016/17:1 utg.omr. 4 s. 49 f). Det är ett pågående arbete som är under beredning inom Regeringskansliet. Således finns det inget ärendenummer eller liknande och det finns inte heller något bestämt datum för när arbetet ska redovisas eller något beslut om hur det ska ske. Det finns därmed inte heller någon projektyta eller delresultat eller liknande som kan redovisas eller lämnas ut. 
>Användningen av ELI (European Legislation Identifier) bygger på principen om frivilligt antagande (se Rådets slutsatser av den 6 november 2017 om European Legislation Identifier [2017/C 441/05]). Frågan om en eventuell implementering av ELI i Sverige har inte varit föremål för något regeringsbeslut. Regeringen har således inte tagit ställning till eller fattat några beslut om en eventuell sådan implementering i Sverige.
>Hälsningar,
>Pontus Hederberg

**Comment by salgo60** [comment]
### Status SFS 1999:175
* [Fråga 2022-12-07](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19#outgoing-3363) status på SFS 1999:175 skickat till Regeringskansliet 
* [Svar 2022.-12-07](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19#incoming-4706) skickar Regeringskansliet det vidare till Justitiedepartementet
* [Svar 2022-12-16](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19) uppfattar jag att Justitiedepartementet inte har något svar utan bollar det tillbaka till Regeringskansliet

## Budgetpropositionen för 2017 prop. 2016/17:1 utg.omr. 4
* [budgetpropositionen för 2017 prop. 2016/17:1 utg.omr. 4](https://www.regeringen.se/4a6969/contentassets/e926a751d9eb4c978c4d892c659ebc8e/utgiftsomrade-4-rattsvasendet)

<img width="478" alt="image" src="https://user-images.githubusercontent.com/14206509/208348165-602178fc-109a-43e4-93b9-28ec818a252c.png">

<img width="476" alt="image" src="https://user-images.githubusercontent.com/14206509/208348257-b8b11333-4163-4adc-85e1-8843ced11cc3.png">

### Min tolkning av Budgetpropositionen för 2017 prop. 2016/17:1 utg.omr. 4
* det saknas en digital vision och mogenhet utan pekar på att SILOS med olika myndigheters författningar är vägen framåt
* att skapa [interoperabilitet](https://www.consilium.europa.eu/sv/press/press-releases/2019/05/14/interoperability-between-eu-information-systems-council-adopts-regulations/) mellan olika myndigheters författningar, [kommuners beslut](https://github.com/salgo60/Anslagstavla/issues/20), [Riksdagens öppna data](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/75), [EU / ELI](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/info/ELI%20ELI-DL.md) förstår inte skribenten ger mervärde utan försöker skriva sig fro från att implementera [SFS 1998:174](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175) dvs. allt detta som pratades i [DS 1998:111]([1996 med en förstudie](https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem) och som ELI pratar om att interoperabilitet i hela Europa ifrågasätts

**Regeringskansliet anges tydligt i dokumentet ovan som ansvarig**

**Comment by salgo60** [comment]
**19 dec 2022** [frågan skickas om till regeringskansliet](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19#outgoing-3382)

**Comment by salgo60** [comment]
Svar **Pontus Hederberg, Regeringskansliet**

```
Hej Magnus,

Tack för ditt mejl om att få ut handlingar och med frågor gällande översyn av rättsinformationsförordningen m.m. Jag har i brev den 13 december skickat ett svar på dina frågor och din begäran men här följer ytterligare ett svar.

Fråga 1 pågår arbete med "översyn av rättsinformationsförordningen"
- I budgetpropositionen för 2017 redovisade regeringen att det i Regeringskansliet pågår en översyn av rättsinformationsförordningen (prop. 2016/17:1 utg.omr. 4 s. 49 f). Det är ett pågående arbete som är under beredning internt inom Regeringskansliet. Budgetpropositionen för 2017 kan du ta del av på följande webbplats: [https://www.regeringen.se/49d951/content...](https://www.regeringen.se/49d951/contentassets/e926a751d9eb4c978c4d892c659ebc8e/budgetpropositionen-for-2017-hela-dokumentet-prop) eller [https://www.regeringen.se/rattsliga-doku...](https://www.regeringen.se/rattsliga-dokument/proposition/2016/09/prop.-2016171/).

Fråga 2 projektnummer
- Det är ett internt arbete.

Fråga 3 när skall det redovisas
- Det finns inget bestämt datum för när arbetet ska redovisas.

Fråga 4 var kan vi följa detta arbete finns projektyta
- Det är ett internt arbete.

Fråga 5 har delresultat publicerats
- Det är ett pågående internt arbete.

Fråga 6 är ELI en del av detta
- Användningen av ELI (European Legislation Identifier) bygger på principen om frivilligt antagande (se Rådets slutsatser av den 6 november 2017 om European Legislation Identifier [2017/C 441/05]). Frågan om en eventuell implementering av ELI i Sverige har inte varit föremål för något regeringsbeslut. Regeringen har således inte tagit ställning till eller fattat några beslut om en eventuell sådan implementering i Sverige.

Det finns således inte några andra allmänna handlingar än budgetpropositionen från 2017 att lämna ut som motsvarar din förfrågan.

Hoppas du är nöjd med svaret.

Med vänliga hälsningar
Pontus Hederberg
Kansliråd
Justitiedepartementet
Kriminalpolitiska enheten
103 33 Stockholm
Tfn 08-405 53 01
Mobil 072-579 69 79
[[e-postadress](https://handlingar.se/help/officers#mobiles)]
[www.regeringen.se](http://www.regeringen.se/)

```

**Comment by salgo60** [comment]
**Summering**
* [Fråga 2022-12-07](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19#outgoing-3363) status på SFS 1999:175 skickat till Regeringskansliet
* [Svar 2022.-12-07](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19#incoming-4706) skickar Regeringskansliet det vidare till Justitiedepartementet
* [Svar 2022-12-13](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19) uppfattar jag att Justitiedepartementet inte har något svar utan bollar det tillbaka till Regeringskansliet med hänvisning till nedanstående budgetproposition
* [Svar 2022-12-19](https://handlingar.se/sv/request/rattsinformationssystemet_sfs_19#incoming-4723) Regeringskansliet har inte status på SFS 1999:175 mer än "Det är ett pågående arbete som är under beredning internt inom Regeringskansliet. Budget"
   * ung. 100 myndigheter med rätt att föreskriva författningar skall leverera **EN** dokumenttyp författningar på samma sätt
   * för 26 år sedan startade en förstudie DS 1998:10
   * för 25 år sedan kom SFS 1999:176
   * för 7 år sedan "gav Domstolsverket upp" att implementera detta
   * 2016 sep 14 pekas Regeringskansliet ut att göra en översyn
   * 2022 dec **efter 6 år har Regeringskansliet inte producerat några allmänna handlingar om detta** 
     * [2022 dec 7 på förfrågan om status på SFS 1999:175](https://github.com/salgo60/LagrummetLight/issues/3#issue-1481419220) verkar Regeringskansliet inte ens veta om att det är deras ansvar utan skickar det till Justitiedepartementet
        * nu 2 veckor senare vet dom att dom skall svara men svarar på ett sätt som **bara kan tolkas som inget gjorts på 6 år**

**Comment by emilv** [comment]
Kontakta Riksrevisionen också.

**Comment by salgo60** [comment]
> Kontakta Riksrevisionen också.

@emilv Tackar min tanke just nu är att vi startar med [20 dec 2022 granskning begärd](https://github.com/salgo60/LagrummetLight/issues/3#issuecomment-1359381679) och ser om någon känner ansvar och tar tag i detta med [SFS 1999:175](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175) och skapa ett Rättsinformatuionssystem seriöst förstudien startade om jag minns rätt för 26 år sedan innan företaget Google grundades... 2017 skriver dom i [Budgetpropositionen att SILOS är bättre](https://github.com/salgo60/LagrummetLight/issues/3#issuecomment-1357092599)...
* gissar att det inte bara en sten som bör lyftas på och granskas.... kan man 2022 inte ens skapa en digital myndighet som nu senast ifrågasätts av deras egen personal så känns det som vi har "a trail of shit" som skapar dessa underleveranser och konstiga tankar som exempel [Budgetpropositionen för 2017 prop. 2016/17:1 utg.omr. 4](https://github.com/salgo60/LagrummetLight/issues/3#issuecomment-1357092599)

Jag har skapat ett antal [skuggbackloggar](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/skuggbacklog.md) med all galenskap jag ser, finns ingen digital kompetens att skapa flöden för rättsväsendet, Riksdagensdokument, nya expertmyndigheten myndigheten DIGG....

**Comment by salgo60** [comment]
## Varför lyckas inte myndigheterna med SFS 1999:175?
Min slutsats är fel laguppställning och en haverirappoort måste tas fram.... 

Vi kan jämför projektet Rättsinformationsförordning [SFS 1999:175](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175) med
* [Swedish parliamentary proceedings - Riksdagens protokoll 1920-2021](https://github.com/welfare-state-analytics/riksdagen-corpus) som har samma komplexitet men en annan laguppställning
   * detta projekt planerar nu att starta del 2 för 5 miljoner skapa en [Kunskapsgraf](https://github.com/salgo60/DiggUptime/issues/78) med denna information ["Sveriges Riksdag 1867–2022: Ett ekosystem av länkad öppen data"](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/84) se [pressrelease nedan]((https://www.umu.se/nyheter/5-miljoner-till-forskning-om-lankad-parlamentariska-data_11678700/))

Riksdagens corpus har även kopplat _samma som_ med [Wikidata](https://www.youtube.com/watch?v=m_9_23jXPoE) som i sin tur kopplar samma som [boken Tvåkammar-riksdagen 1867-1970](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38) och många andra

### Hur Riksdagstrycket har _Samma som_ Wikidata dvs. interoperabilitet
Projektet "Swedish parliamentary proceedings" använder [TEI Parla-Clarin](https://clarin-eric.github.io/parla-clarin/) dom märker upp vem som prata med

> <u who="Q5711655" ....

där [Q5711655](https://w.wiki/5gP3) är Wikidata Persistenta Identifieraren för [Riksdagsmannen Arthur Engberg](https://sv.wikipedia.org/wiki/Arthur_Engberg) intressant är att detta görs i flera länder se [Parla-mint](https://www.clarin.eu/parlamint)

[![](https://user-images.githubusercontent.com/14206509/187056803-dfc206e1-6014-4789-8f12-78db06df8fef.png)](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38#issuecomment-1229370127)

[<img width="1030" alt="image" src="https://user-images.githubusercontent.com/14206509/211146749-e01d6c5d-d3d5-4f3c-97c5-377d023766a7.png">](https://www.umu.se/nyheter/5-miljoner-till-forskning-om-lankad-parlamentariska-data_11678700/)

**Comment by salgo60** [comment]
Intressant kommentar av [Niklas Lindström från Kungliga biblioteket](https://www.kb.se/samverkan-och-utveckling/nytt-fran-kb/nyheter-samverkan-och-utveckling/2019-09-25-presentations-from-the-3rd-annual-bibframe-workshop-in-europe.html) som var del av projektet och kunnig som idag 2022 finns på Kungliga Biblioteket i [ett annat mer eller mindre dysfunktionellt projekt #77-11](https://github.com/salgo60/DiggUptime/issues/77#issuecomment-1319779092)

* [länk svar om vad som behövs med länkade data](https://youtu.be/xZDljVBEt5Q?t=3320)

> man måste äga frågan som organisation

Gissar att det är lärdommar av att jobba med 100 myndigheter och Rättsinformationssystemet under flera år

**Comment by salgo60** [comment]
* [Riksrevisionen så granskar vi](https://www.riksrevisionen.se/metoder.html) tel: 0734452064

**Comment by salgo60** [comment]
**Ingen återkoppling från Regeringskansliet** på förfrågan  [20 dec 2022](https://github.com/salgo60/LagrummetLight/issues/3#issuecomment-1359381679)

**Jag antar att det är ett exempel på tjänstemannens förhalning att inte återkoppla på en fråga om varför inget har hänt efter 20 år**

**Comment by salgo60** [comment]
## 8 december 2023 Uppdrag om en säker och effektiv tillgång till rättsinformation
_[Regeringen har gett Domstolsverket i uppdrag att analysera hur det offentliga rättsinformationssystemet kan utvecklas](https://www.regeringen.se/pressmeddelanden/2023/12/uppdrag-om-en-saker-och-effektiv-tillgang-till-rattsinformation/)._ 


<img width="1217" alt="image" src="https://github.com/salgo60/LagrummetLight/assets/14206509/c3f5a87c-e0a3-4aed-a366-d5ed390784ec">

**Comment by salgo60** [comment]
Verkar som denna förfrågan gett upphov rill #8 - Ju2023/02684 

Udda att detta inte återrapporteras till mig. Känns som en öppen publik backlog bör finnas där man kan följa sina ärenden... Regeringskansliet är långt från att vara datadrivna och "kundorienterade"
